/* eslint-disable */
const metadata = {
    fields: {
        space: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            name: {
                name: 'name',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            slug: {
                name: 'slug',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            members: {
                name: 'members',
                type: 'SpaceUser',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'space',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            lists: {
                name: 'lists',
                type: 'List',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'space',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        spaceUser: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            space: {
                name: 'space',
                type: 'Space',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'members',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'spaceId' },
            },
            spaceId: {
                name: 'spaceId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            user: {
                name: 'user',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'spaces',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'userId' },
            },
            userId: {
                name: 'userId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            role: {
                name: 'role',
                type: 'SpaceUserRole',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        user: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            email: {
                name: 'email',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            emailVerified: {
                name: 'emailVerified',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            password: {
                name: 'password',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            name: {
                name: 'name',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            spaces: {
                name: 'spaces',
                type: 'SpaceUser',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            image: {
                name: 'image',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            lists: {
                name: 'lists',
                type: 'List',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'owner',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            todos: {
                name: 'todos',
                type: 'Todo',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'owner',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            accounts: {
                name: 'accounts',
                type: 'Account',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        list: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            space: {
                name: 'space',
                type: 'Space',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'lists',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'spaceId' },
            },
            spaceId: {
                name: 'spaceId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            owner: {
                name: 'owner',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'lists',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'ownerId' },
            },
            ownerId: {
                name: 'ownerId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            title: {
                name: 'title',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            private: {
                name: 'private',
                type: 'Boolean',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            todos: {
                name: 'todos',
                type: 'Todo',
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'list',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        todo: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            createdAt: {
                name: 'createdAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            updatedAt: {
                name: 'updatedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            owner: {
                name: 'owner',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'todos',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'ownerId' },
            },
            ownerId: {
                name: 'ownerId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            list: {
                name: 'list',
                type: 'List',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'todos',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'listId' },
            },
            listId: {
                name: 'listId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            title: {
                name: 'title',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            completedAt: {
                name: 'completedAt',
                type: 'DateTime',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
        },
        account: {
            id: {
                name: 'id',
                type: 'String',
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            userId: {
                name: 'userId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined,
            },
            type: {
                name: 'type',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            provider: {
                name: 'provider',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            providerAccountId: {
                name: 'providerAccountId',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            refresh_token: {
                name: 'refresh_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            refresh_token_expires_in: {
                name: 'refresh_token_expires_in',
                type: 'Int',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            access_token: {
                name: 'access_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            expires_at: {
                name: 'expires_at',
                type: 'Int',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            token_type: {
                name: 'token_type',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            scope: {
                name: 'scope',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            id_token: {
                name: 'id_token',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            session_state: {
                name: 'session_state',
                type: 'String',
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined,
            },
            user: {
                name: 'user',
                type: 'User',
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'accounts',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { id: 'userId' },
            },
        },
    },
    uniqueConstraints: {
        space: {
            id: {
                name: 'id',
                fields: ['id'],
            },
            slug: {
                name: 'slug',
                fields: ['slug'],
            },
        },
        spaceUser: {
            userId_spaceId: {
                name: 'userId_spaceId',
                fields: ['userId', 'spaceId'],
            },
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        user: {
            id: {
                name: 'id',
                fields: ['id'],
            },
            email: {
                name: 'email',
                fields: ['email'],
            },
        },
        list: {
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        todo: {
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
        account: {
            provider_providerAccountId: {
                name: 'provider_providerAccountId',
                fields: ['provider', 'providerAccountId'],
            },
            id: {
                name: 'id',
                fields: ['id'],
            },
        },
    },
    deleteCascade: {
        space: ['SpaceUser', 'List'],
        user: ['SpaceUser', 'List', 'Todo', 'Account'],
        list: ['Todo'],
    },
    authModel: 'User',
};
export default metadata;
